default_language_version:
    python:  python3.7

repos:

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.7
      args: ['--target-version=py37']

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-blind-except>=0.1.1]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: check-ast
    - id: check-merge-conflict
    - id: check-added-large-files
      args: ['--maxkb=600']
